config/routes.rb
Rails.application.routes.draw do
  
  resources :projects do
    resources :tasks do 
      member do
        patch :complete
      end
    end
  end
 
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  def completed?
    !completed_at.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [ :show, :edit, :update, :destroy]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
before_action :set_project
before_action :set_task, except: [:create]

def create
@task = @project.tasks.create(task_params)
redirect_to @project
end

def destroy
    
    if @task.destroy
        flash[:success] = "Task was deleted."
    else
        flash[:error] = "Task was not deleted."
end
redirect_to @project
end

def complete
    @task.update_attribute(:completed_at,Time.now)
    redirect_to @project, notice: "Task completed"
end

private

def set_project
    @project = Project.find(params[:project_id])
end


def set_task
    @task =@project.tasks.find(params[:id])
end

def task_params
    params[:task].permit(:content)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Title:</strong>
    <%= project.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p id="notice"> <%= notice %> </p>

<p>
<strong>title:</strong>
<%= @project.title %>
</p>

<p>
<strong>Description:</strong>
<%= @project.description %>
</p>

<div id="todo_items_wrapper">
      <%= render @project.tasks %>
  <div id="form">
      <%= render "tasks/form" %>
  </div>
</div>

<%= link_to 'Edit', edit_project_path(@project) %>
<%= link_to 'Back', projects_path %>

app/views/tasks/_form.html.erb
<%= form_for([@project, @project.tasks.build]) do |f| %>
<%= f.text_field :content,placeholder: "New Task" %>
<%= f.submit %>
<% end %>

app/views/tasks/_task.html.erb
<p><%=task.content %></p>
<%= link_to "Delete", project_task_path(@project, task.id), method: :delete, data: { confirm: "Are you sure?" } %>

<%= link_to "Mark as completed",complete_project_task_path(@project, task.id), method: :patch %>


<div class="row clearfix">
<%  if task.completed? %>
<div class="complete">

     <%= link_to "Mark as completed",complete_project_task_path(@project, task.id), method: :patch %>
</div>
<div class="task">
<p style ="opacity: 0.4;"><strike><%= task.content %></strike></p>
</div>

<div class="trash">
<%= link_to "Delete", project_task_path(@project, task.id), method: :delete, data: { confirm: "Are you sure?" } %>
</div>

<% else %>

<div class="complete">

     <%= link_to "Mark as completed",complete_project_task_path(@project, task.id), method: :patch %>
</div>
<div class="task">
<p><%= task.content %></p>
</div>

<div class="trash">
<%= link_to "Delete", project_task_path(@project, task.id), method: :delete, data: { confirm: "Are you sure?" } %>
</div>
<% end %>
</div>